name: Publish Feed

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "publish" to confirm publishing the feed'
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'publish'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Publish feed
        run: npm run publish
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Success
        run: echo "Feed published successfully! 🚀"
