name: Publish Feed

on:
  workflow_dispatch:
    inputs:
      recordName:
        description: "ID of the feed, visible in the URL. Unique within your account. Using an existing ID will overwrite the existing feed on the same account."
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Publish feed
        run: npm run publish ${{ github.event.inputs.recordName }}
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Success
        run: echo "Feed published successfully! 🚀"
