name: Unpublish Feed

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "unpublish" to confirm unpublishing the feed'
        required: true
        type: string

permissions:
  contents: read

jobs:
  unpublish:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'unpublish'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Unpublish feed
        run: npm run unpublish
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Success
        run: echo "Feed unpublished successfully! 🗑️"
